/*

*/
package interfaz;

import javax.swing.table.DefaultTableModel;
import datos.Conexion;
import java.sql.*;
import javax.swing.JOptionPane;

public class AdministrarMedicos extends javax.swing.JInternalFrame {

    Conexion enlace = new Conexion();
    Connection connect;
    
    public AdministrarMedicos() throws SQLException {
        this.connect = enlace.getConnection();
        initComponents();
        mostrarDatosMedicos();
    }
    public void mostrarDatosMedicos(){
        
        DefaultTableModel tMedicos = new DefaultTableModel();
        
        tMedicos.addColumn("CodigoTarjetaProfesional");
        tMedicos.addColumn("Especialidad");
        tMedicos.addColumn("AñosExperiencia");
        tMedicos.addColumn("Consultorio");
        tMedicos.addColumn("Domicilio");
        
        tablaMedicos.setModel(tMedicos);
        
        String[] datos = new String[5];
        
        try{
            Statement leer = connect.createStatement();
            ResultSet resultado = leer.executeQuery("SELECT * FROM medicos");
            
            while(resultado.next()){
                datos[0] = resultado.getString(1);
                datos[1] = resultado.getString(2);
                datos[2] = resultado.getString(3);
                datos[3] = resultado.getString(4);
                datos[4] = resultado.getString(5);
                
                tMedicos.addRow(datos);
            }
            tablaMedicos.setModel(tMedicos);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e, "Error en SELECT Medicos",2);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMedicos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tabla Medicos");

        tablaMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaMedicos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMedicos;
    // End of variables declaration//GEN-END:variables
}
