
package interfaz;

import javax.swing.table.DefaultTableModel;
import datos.Conexion;
import java.sql.*;
import javax.swing.JOptionPane;

public class AdministrarPacientes extends javax.swing.JInternalFrame {

    Conexion enlace = new Conexion();
    Connection connect;
    
    public AdministrarPacientes() throws SQLException{
        this.connect = enlace.getConnection();
        initComponents();
        mostrarDatosPacientes();
    }
    public void mostrarDatosPacientes(){
        DefaultTableModel tPacientes = new DefaultTableModel();
        
        tPacientes.addColumn("Nombres");
        tPacientes.addColumn("Apellidos");
        tPacientes.addColumn("Fecha Nacimiento");
        tPacientes.addColumn("Identificacion");
        tPacientes.addColumn("Medico");
        tPacientes.addColumn("Tratamiento");
        tPacientes.addColumn("Cuota Moderadora");
        tPacientes.addColumn("Fecha Hora Nueva Cita");
        tPacientes.addColumn("Firma Paciente");
        tPacientes.addColumn("Fecha Llegada Cita");
        
        tablaPacientes.setModel(tPacientes);
        
        String[] datos = new String[10];
        try {
            Statement leer = connect.createStatement();
            ResultSet resultado = leer.executeQuery("SELECT * FROM paciente");
            
            while(resultado.next()){
                datos[0] = resultado.getString(1);
                datos[1] = resultado.getString(2);
                datos[2] = resultado.getString(3);
                datos[3] = resultado.getString(4);
                datos[4] = resultado.getString(5);
                datos[5] = resultado.getString(6);
                datos[6] = resultado.getString(7);
                datos[7] = resultado.getString(8);
                datos[8] = resultado.getString(9);
                datos[9] = resultado.getString(10);
                
                tPacientes.addRow(datos);
            }
            tablaPacientes.setModel(tPacientes);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e,"Error en SELECT Pacientes",2);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPacientes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Tabla Pacientes");

        tablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(tablaPacientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPacientes;
    // End of variables declaration//GEN-END:variables
}
