/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaz;

import datos.pacienteJDBC;
import dominios.Paciente;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import datos.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author MARTHA
 */
public class LlegadaPacientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form LlegadaPacientes
     */
    public LlegadaPacientes() {
        initComponents();
        fechaTextField();
    }
    private void fechaTextField(){
        LocalDate fechaActual = LocalDate.now();
        
        fechaLlegadaTextField.setText(fechaActual.toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigoTarjetaProfesionalTextField = new javax.swing.JTextField();
        identificacionPacienteTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        firmaPacienteTextField = new javax.swing.JTextField();
        fechaLlegadaTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jLabel1.setText("Identificación Paciente:");

        jLabel2.setText("Codigo Tarjeta Profesional Medico:");

        jLabel3.setText("Firma Paciente:");

        jLabel5.setText("Fecha Llegada:");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(identificacionPacienteTextField)
                    .addComponent(codigoTarjetaProfesionalTextField)
                    .addComponent(firmaPacienteTextField)
                    .addComponent(fechaLlegadaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoTarjetaProfesionalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(identificacionPacienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(firmaPacienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fechaLlegadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            boolean haveMedico = false;
            
            Conexion enlace = new Conexion();
            Connection connect;
            connect = enlace.getConnection();
            
            ArrayList medicos = new ArrayList();
            
            Statement leer = connect.createStatement();
            ResultSet resultado = leer.executeQuery("SELECT Medico FROM paciente");
            
            while(resultado.next()){
                medicos.add(resultado.getString(1));
            }
            for(int i=0;i<medicos.size();i++){
                System.out.println("medicos: "+medicos.get(i) + " codigo: "+codigoTarjetaProfesionalTextField.getText());
                if(medicos.get(i).equals(codigoTarjetaProfesionalTextField.getText())){
                    haveMedico = true;
                    break;
                }
            }
            if(haveMedico){
                Paciente objetoPaciente = new Paciente();
                pacienteJDBC objetoPacienteJDBC = new pacienteJDBC();

                objetoPaciente.setFirmaPaciente(firmaPacienteTextField.getText());
                objetoPaciente.setFechaLlegadaCita(fechaLlegadaTextField.getText());
                objetoPaciente.setIdentificacion(identificacionPacienteTextField.getText());
                objetoPaciente.setMedicoAsignado(codigoTarjetaProfesionalTextField.getText());

                objetoPacienteJDBC.insertWhere(objetoPaciente);
                JOptionPane.showMessageDialog(this,"Actualizado correctamente en la tabla Paciente" , "Actualizar correctamete", 1);
            }else{
                JOptionPane.showMessageDialog(this,"El codigo de tarjeta Profesional: "+codigoTarjetaProfesionalTextField.getText()+"\nNo Tiene Asignado ningún Paciente");
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,ex , "Error en Insertar", 1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoTarjetaProfesionalTextField;
    private javax.swing.JTextField fechaLlegadaTextField;
    private javax.swing.JTextField firmaPacienteTextField;
    private javax.swing.JTextField identificacionPacienteTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
